# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['visualizer_app.py'],
    pathex=[],
    binaries=[],
    datas=[
        # Assets de la app
        ('icon.ico', '.'),
        ('icon.png', '.'),
        ('splash.png', '.'),
        ('author.png', '.'),
        ('app/assets/*.png', 'app/assets'),
    ],
    hiddenimports=[
        # App modules (imports dinámicos dentro de funciones)
        'app.main',
        'app.config',
        'app.i18n',
        'app.utils.paths',
        'app.utils.fonts',
        'app.core.audio',
        'app.core.video',
        'app.core.kinetic_pil',
        'app.core.spot',
        'app.core.platforms',
        'app.core.project',
        'app.core.timestamps',
        'app.core.render_worker',
        'app.core.renderer',
        'app.scripts.lyric_video',
        'app.scripts.lyric_video_manim',
        'app.scripts.generar_timestamps',
        'app.ui.app',
        'app.ui.about',
        'app.ui.toolbar',
        'app.ui.splash',
        'app.ui.help_window',
        'app.ui.settings',
        'app.ui.sync_editor',
        'app.ui.components',
        'app.ui.panels.files_panel',
        'app.ui.panels.config_panel',
        'app.ui.panels.spot_panel',
        'app.ui.panels.preview_panel',
        # Librerías con imports dinámicos
        'PIL', 'PIL.Image', 'PIL.ImageDraw', 'PIL.ImageFont',
        'PIL.ImageFilter', 'PIL.ImageEnhance', 'PIL.ImageTk',
        'customtkinter',
        'tkinter', 'tkinter.filedialog', 'tkinter.ttk', 'tkinter.messagebox',
        'moviepy', 'moviepy.audio.io.AudioFileClip',
        'moviepy.video.VideoClip', 'moviepy.video.io.VideoFileClip',
        'librosa',
        'numpy',
        'cv2',
        'qrcode',
        'pygame',
        'psutil',
        'winreg',
        'ctypes',
        'multiprocessing',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Opcionales pesados que NO necesitamos en el bundle
        'manim', 'manimpango',
        'anthropic', 'openai',
        'torch', 'whisper',
        'matplotlib', 'scipy',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='DudiverVisualizer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['icon.ico'],
)
